export const themeValues = [
  {
    title: "General colors",
    themeProps: [
      {
        title: "Primary font color",
        defaultValue: "#000000",
        defaultType: "color",
        variableName: "colors.primary",
        equivalentCssProperty: "color",
      },
      {
        title: "Primary background color",
        defaultValue: "#ffffff",
        defaultType: "color",
        variableName: "colors.primaryBackground",
        equivalentCssProperty: "color",
      },
      {
        title: "Secondary font color",
        defaultValue: "#ffffff",
        defaultType: "color",
        variableName: "colors.secondary",
        equivalentCssProperty: "color",
      },
      {
        title: "Secondary background color",
        defaultValue: "#4a86e8",
        defaultType: "color",
        variableName: "colors.secondaryBackground",
        equivalentCssProperty: "color",
      },
      {
        title: "Highlight on primary background",
        defaultValue: "#4a86e8",
        defaultType: "color",
        variableName: "colors.highlight1",
        equivalentCssProperty: "color",
      },
      {
        title: "Highlight on secondary background",
        defaultValue: "#ffab40",
        defaultType: "color",
        variableName: "colors.highlight2",
        equivalentCssProperty: "color",
      },
    ],
  },
  {
    title: "Global sizes",
    themeProps: [
      {
        title: "Default text size",
        defaultValue: "1.1",
        defaultType: "em",
        variableName: "sizes.text",
        equivalentCssProperty: "fontSize",
      },
      {
        title: "Header1 text size",
        defaultValue: "1.4",
        defaultType: "em",
        variableName: "sizes.h1",
        equivalentCssProperty: "fontSize",
      },
      {
        title: "Header2 text size",
        defaultValue: "1.2",
        defaultType: "em",
        variableName: "sizes.h2",
        equivalentCssProperty: "fontSize",
      },
      {
        title: "Default border width",
        defaultValue: "1",
        defaultType: "px",
        variableName: "sizes.borderWidth",
        equivalentCssProperty: "borderWidth",
      },
    ],
  },
  {
    title: "Text field",
    themeProps: [
      {
        title: "Text size",
        defaultValue: "1.1",
        defaultType: "em",
        variableName: "textfield.textSize",
        equivalentCssProperty: "fontSize",
      },
      {
        title: "Font color",
        defaultValue: "#000000",
        defaultType: "color",
        variableName: "textfield.color",
        equivalentCssProperty: "color",
      },
      {
        title: "Border",
        defaultValue: "1px solid #000000",
        defaultType: "text",
        variableName: "textfield.border",
        equivalentCssProperty: "border",
      },
      {
        title: "Background",
        defaultValue: "#ffffff",
        defaultType: "color",
        variableName: "textfield.background",
        equivalentCssProperty: "background",
      },
    ],
  },
  {
    title: "Buttons",
    themeProps: [
      {
        title: "Font size",
        defaultValue: "calc(1.1rem*1.2)",
        defaultType: "text",
        variableName: "buttons.fontSize",
        equivalentCssProperty: "fontSize",
      },
      {
        title: "Font color",
        defaultValue: "#000000",
        defaultType: "color",
        variableName: "buttons.color",
        equivalentCssProperty: "color",
      },
      {
        title: "Background",
        defaultValue: "#4a86e8",
        defaultType: "color",
        variableName: "buttons.background",
        equivalentCssProperty: "background",
      },
    ],
  },
  {
    title: "Icon",
    themeProps: [
      {
        title: "Icon color",
        defaultValue: "blue",
        defaultType: "color",
        variableName: "icon.color",
        equivalentCssProperty: "color",
      },
      {
        title: "Icon width",
        defaultValue: "10",
        defaultType: "px",
        variableName: "icon.width",
        equivalentCssProperty: "width",
      },
      {
        title: "Icon height",
        defaultValue: "10",
        defaultType: "px",
        variableName: "icon.height",
        equivalentCssProperty: "height",
      },
    ],
  },
  {
    title: 'General padding',
    themeProps: [
      {
        title: "Title padding",
        defaultValue: '2',
        defaultType: 'px',
        variableName: 'padding.title',
        equivalentCssProperty: 'padding',
      },
      {
        title: "Button padding",
        defaultValue: '5',
        defaultType: 'px',
        variableName: 'padding.button',
        equivalentCssProperty: 'padding',
      },
      {
        title: "Icon padding",
        defaultValue: '1',
        defaultType: 'px',
        variableName: 'padding.icon',
        equivalentCssProperty: 'padding',
      },
    ],
  },
];